import type {
  Process,
  TeamMember,
  Insight,
  ActivityItem,
  TrendDataPoint,
  Notification,
} from "@/types";

export const TEAM_MEMBERS: TeamMember[] = [
  {
    id: "u1",
    name: "Sarah Chen",
    email: "sarah.chen@acme.io",
    role: "admin",
    initials: "SC",
    color: "#6366f1",
    processesOwned: 4,
    lastActive: "2026-04-09T10:23:00Z",
  },
  {
    id: "u2",
    name: "Marcus Webb",
    email: "marcus.webb@acme.io",
    role: "member",
    initials: "MW",
    color: "#06b6d4",
    processesOwned: 3,
    lastActive: "2026-04-09T09:45:00Z",
  },
  {
    id: "u3",
    name: "Priya Nair",
    email: "priya.nair@acme.io",
    role: "member",
    initials: "PN",
    color: "#10b981",
    processesOwned: 2,
    lastActive: "2026-04-08T17:10:00Z",
  },
  {
    id: "u4",
    name: "Luca Ferretti",
    email: "luca.ferretti@acme.io",
    role: "viewer",
    initials: "LF",
    color: "#f59e0b",
    processesOwned: 0,
    lastActive: "2026-04-07T14:30:00Z",
  },
  {
    id: "u5",
    name: "Aisha Okafor",
    email: "aisha.okafor@acme.io",
    role: "member",
    initials: "AO",
    color: "#ec4899",
    processesOwned: 1,
    lastActive: "2026-04-09T11:00:00Z",
  },
];

export const PROCESSES: Process[] = [
  {
    id: "p1",
    name: "Customer Onboarding",
    description: "End-to-end onboarding flow from signup to first value moment",
    status: "active",
    teamId: "t1",
    avgCycleTimeHours: 72,
    completionRate: 68,
    version: 4,
    tags: ["customer-success", "growth"],
    createdAt: "2026-01-15T09:00:00Z",
    updatedAt: "2026-04-07T15:30:00Z",
    nodes: [
      {
        id: "n1",
        type: "task",
        label: "Signup & Verification",
        description: "User creates account, email verification sent",
        avgDurationHours: 0.5,
        bottleneckScore: 10,
        assignee: "u2",
        team: "Engineering",
        comments: [],
        position: { x: 80, y: 200 },
      },
      {
        id: "n2",
        type: "task",
        label: "Profile Setup",
        description: "User fills out company & role details",
        avgDurationHours: 1.5,
        bottleneckScore: 22,
        assignee: "u3",
        team: "Product",
        comments: [],
        position: { x: 280, y: 200 },
      },
      {
        id: "n3",
        type: "decision",
        label: "Plan Selection",
        description: "User selects pricing plan or starts free trial",
        avgDurationHours: 4.0,
        bottleneckScore: 55,
        assignee: "u1",
        team: "Sales",
        comments: [
          {
            id: "c1",
            userId: "u1",
            userName: "Sarah Chen",
            userInitials: "SC",
            userColor: "#6366f1",
            content:
              "Conversion rate here dropped 12% this quarter. We need to revisit the pricing page.",
            createdAt: "2026-04-08T10:00:00Z",
          },
        ],
        position: { x: 480, y: 200 },
      },
      {
        id: "n4",
        type: "delay",
        label: "Manual Review Queue",
        description: "Enterprise signups await manual review by Sales",
        avgDurationHours: 28,
        bottleneckScore: 87,
        assignee: "u1",
        team: "Sales",
        comments: [],
        position: { x: 680, y: 100 },
      },
      {
        id: "n5",
        type: "task",
        label: "Workspace Provisioning",
        description: "Automated provisioning of workspace and default templates",
        avgDurationHours: 0.25,
        bottleneckScore: 8,
        assignee: "u2",
        team: "Engineering",
        comments: [],
        position: { x: 680, y: 300 },
      },
      {
        id: "n6",
        type: "external",
        label: "Welcome Email Sequence",
        description: "Automated 3-email onboarding sequence via Mailchimp",
        avgDurationHours: 48,
        bottleneckScore: 30,
        assignee: "u3",
        team: "Marketing",
        comments: [],
        position: { x: 880, y: 200 },
      },
      {
        id: "n7",
        type: "task",
        label: "First Value Moment",
        description: "User completes first meaningful action in the product",
        avgDurationHours: 2,
        bottleneckScore: 42,
        assignee: "u5",
        team: "Product",
        comments: [],
        position: { x: 1080, y: 200 },
      },
    ],
    edges: [
      { id: "e1-2", source: "n1", target: "n2" },
      { id: "e2-3", source: "n2", target: "n3" },
      { id: "e3-4", source: "n3", target: "n4", label: "Enterprise" },
      { id: "e3-5", source: "n3", target: "n5", label: "Self-serve" },
      { id: "e4-6", source: "n4", target: "n6" },
      { id: "e5-6", source: "n5", target: "n6" },
      { id: "e6-7", source: "n6", target: "n7", animated: true },
    ],
  },
  {
    id: "p2",
    name: "Bug Resolution Workflow",
    description: "From bug report to production fix — tracking all handoffs",
    status: "active",
    teamId: "t1",
    avgCycleTimeHours: 38,
    completionRate: 91,
    version: 2,
    tags: ["engineering", "quality"],
    createdAt: "2026-02-01T10:00:00Z",
    updatedAt: "2026-04-09T08:00:00Z",
    nodes: [
      {
        id: "n1",
        type: "external",
        label: "Bug Reported",
        description: "Issue logged via Sentry, Jira, or customer support",
        avgDurationHours: 0.1,
        bottleneckScore: 5,
        assignee: "u2",
        team: "Engineering",
        comments: [],
        position: { x: 80, y: 200 },
      },
      {
        id: "n2",
        type: "decision",
        label: "Severity Triage",
        description: "Engineering lead assigns severity: P1/P2/P3",
        avgDurationHours: 3,
        bottleneckScore: 45,
        assignee: "u2",
        team: "Engineering",
        comments: [],
        position: { x: 280, y: 200 },
      },
      {
        id: "n3",
        type: "task",
        label: "P1 Hotfix Track",
        description: "Immediate fix, skip QA queue",
        avgDurationHours: 4,
        bottleneckScore: 20,
        assignee: "u2",
        team: "Engineering",
        comments: [],
        position: { x: 480, y: 80 },
      },
      {
        id: "n4",
        type: "task",
        label: "Sprint Backlog",
        description: "P2/P3 added to next sprint",
        avgDurationHours: 120,
        bottleneckScore: 78,
        assignee: "u2",
        team: "Engineering",
        comments: [],
        position: { x: 480, y: 320 },
      },
      {
        id: "n5",
        type: "task",
        label: "Code Fix & Review",
        description: "Developer implements fix, code review by peers",
        avgDurationHours: 6,
        bottleneckScore: 35,
        assignee: "u2",
        team: "Engineering",
        comments: [],
        position: { x: 680, y: 200 },
      },
      {
        id: "n6",
        type: "task",
        label: "QA Validation",
        description: "QA verifies fix in staging environment",
        avgDurationHours: 8,
        bottleneckScore: 62,
        assignee: "u3",
        team: "QA",
        comments: [],
        position: { x: 880, y: 200 },
      },
      {
        id: "n7",
        type: "task",
        label: "Deploy to Production",
        description: "Merge to main, automated deployment pipeline",
        avgDurationHours: 0.5,
        bottleneckScore: 12,
        assignee: "u2",
        team: "Engineering",
        comments: [],
        position: { x: 1080, y: 200 },
      },
    ],
    edges: [
      { id: "e1-2", source: "n1", target: "n2" },
      { id: "e2-3", source: "n2", target: "n3", label: "P1" },
      { id: "e2-4", source: "n2", target: "n4", label: "P2/P3" },
      { id: "e3-5", source: "n3", target: "n5" },
      { id: "e4-5", source: "n4", target: "n5" },
      { id: "e5-6", source: "n5", target: "n6" },
      { id: "e6-7", source: "n6", target: "n7", animated: true },
    ],
  },
  {
    id: "p3",
    name: "Product Launch Checklist",
    description: "Coordinated go-to-market process across all teams",
    status: "optimizing",
    teamId: "t1",
    avgCycleTimeHours: 336,
    completionRate: 55,
    version: 1,
    tags: ["product", "go-to-market"],
    createdAt: "2026-03-10T09:00:00Z",
    updatedAt: "2026-04-05T12:00:00Z",
    nodes: [
      {
        id: "n1",
        type: "task",
        label: "Feature Freeze",
        description: "Engineering locks feature scope",
        avgDurationHours: 1,
        bottleneckScore: 15,
        assignee: "u2",
        team: "Engineering",
        comments: [],
        position: { x: 80, y: 200 },
      },
      {
        id: "n2",
        type: "task",
        label: "Docs & Changelog",
        description: "Write release notes and update documentation",
        avgDurationHours: 24,
        bottleneckScore: 70,
        assignee: "u3",
        team: "Product",
        comments: [],
        position: { x: 280, y: 200 },
      },
      {
        id: "n3",
        type: "task",
        label: "Marketing Assets",
        description: "Blog post, social content, email campaign creation",
        avgDurationHours: 48,
        bottleneckScore: 82,
        assignee: "u5",
        team: "Marketing",
        comments: [],
        position: { x: 480, y: 200 },
      },
      {
        id: "n4",
        type: "delay",
        label: "Legal Sign-off",
        description: "Legal review of new terms or privacy changes",
        avgDurationHours: 72,
        bottleneckScore: 91,
        assignee: "u1",
        team: "Legal",
        comments: [],
        position: { x: 680, y: 200 },
      },
      {
        id: "n5",
        type: "task",
        label: "Launch Day",
        description: "Coordinated launch across all channels",
        avgDurationHours: 4,
        bottleneckScore: 25,
        assignee: "u1",
        team: "All",
        comments: [],
        position: { x: 880, y: 200 },
      },
    ],
    edges: [
      { id: "e1-2", source: "n1", target: "n2" },
      { id: "e2-3", source: "n2", target: "n3" },
      { id: "e3-4", source: "n3", target: "n4" },
      { id: "e4-5", source: "n4", target: "n5", animated: true },
    ],
  },
  {
    id: "p4",
    name: "Invoice Processing",
    description: "AP workflow from invoice receipt to payment approval",
    status: "draft",
    teamId: "t1",
    avgCycleTimeHours: 96,
    completionRate: 74,
    version: 1,
    tags: ["finance", "operations"],
    createdAt: "2026-04-01T10:00:00Z",
    updatedAt: "2026-04-09T09:00:00Z",
    nodes: [
      {
        id: "n1",
        type: "external",
        label: "Invoice Received",
        description: "Email or portal submission",
        avgDurationHours: 0.1,
        bottleneckScore: 5,
        assignee: "u4",
        team: "Finance",
        comments: [],
        position: { x: 80, y: 200 },
      },
      {
        id: "n2",
        type: "task",
        label: "Data Extraction",
        description: "OCR + manual verification of invoice fields",
        avgDurationHours: 2,
        bottleneckScore: 40,
        assignee: "u4",
        team: "Finance",
        comments: [],
        position: { x: 280, y: 200 },
      },
      {
        id: "n3",
        type: "decision",
        label: "Amount Threshold",
        description: "Over $10k requires additional approval",
        avgDurationHours: 0.5,
        bottleneckScore: 20,
        assignee: "u4",
        team: "Finance",
        comments: [],
        position: { x: 480, y: 200 },
      },
      {
        id: "n4",
        type: "delay",
        label: "Manager Approval",
        description: "Awaiting manager sign-off for large invoices",
        avgDurationHours: 48,
        bottleneckScore: 88,
        assignee: "u1",
        team: "Management",
        comments: [],
        position: { x: 680, y: 80 },
      },
      {
        id: "n5",
        type: "task",
        label: "Auto-Approve",
        description: "Invoices under threshold auto-approved",
        avgDurationHours: 0.1,
        bottleneckScore: 3,
        assignee: "u4",
        team: "Finance",
        comments: [],
        position: { x: 680, y: 320 },
      },
      {
        id: "n6",
        type: "task",
        label: "Payment Scheduled",
        description: "Payment queued in net-30 cycle",
        avgDurationHours: 1,
        bottleneckScore: 15,
        assignee: "u4",
        team: "Finance",
        comments: [],
        position: { x: 880, y: 200 },
      },
    ],
    edges: [
      { id: "e1-2", source: "n1", target: "n2" },
      { id: "e2-3", source: "n2", target: "n3" },
      { id: "e3-4", source: "n3", target: "n4", label: ">$10k" },
      { id: "e3-5", source: "n3", target: "n5", label: "<$10k" },
      { id: "e4-6", source: "n4", target: "n6" },
      { id: "e5-6", source: "n5", target: "n6", animated: true },
    ],
  },
];

export const INSIGHTS: Insight[] = [
  {
    id: "i1",
    type: "delay",
    severity: "critical",
    title: "Manual Review Queue causing 39% of cycle time",
    description:
      "The 'Manual Review Queue' node in Customer Onboarding averages 28h — nearly 2x the expected SLA. Consider automating initial qualification.",
    processId: "p1",
    processName: "Customer Onboarding",
    nodeId: "n4",
    impactPercent: 39,
    createdAt: "2026-04-09T06:00:00Z",
  },
  {
    id: "i2",
    type: "bottleneck",
    severity: "critical",
    title: "Legal Sign-off blocking Product Launch",
    description:
      "Legal review averages 72h and has a bottleneck score of 91. This single step accounts for 21% of total launch cycle time.",
    processId: "p3",
    processName: "Product Launch Checklist",
    nodeId: "n4",
    impactPercent: 21,
    createdAt: "2026-04-08T12:00:00Z",
  },
  {
    id: "i3",
    type: "handoff",
    severity: "warning",
    title: "4 team handoffs in Bug Resolution",
    description:
      "The Bug Resolution Workflow involves 4 different teams. Each handoff introduces an average 2.3h context-switch delay.",
    processId: "p2",
    processName: "Bug Resolution Workflow",
    impactPercent: 24,
    createdAt: "2026-04-08T09:00:00Z",
  },
  {
    id: "i4",
    type: "efficiency",
    severity: "warning",
    title: "Sprint Backlog is a P2/P3 graveyard",
    description:
      "78% bottleneck score on the Sprint Backlog node. Bugs assigned to sprint backlog sit for an average of 5 days before being addressed.",
    processId: "p2",
    processName: "Bug Resolution Workflow",
    nodeId: "n4",
    impactPercent: 32,
    createdAt: "2026-04-07T15:00:00Z",
  },
  {
    id: "i5",
    type: "delay",
    severity: "warning",
    title: "Manager Approval averaging 48h in Invoice Processing",
    description:
      "Invoices over $10k are blocked waiting for manager approval. Consider delegating approval authority or implementing async notifications.",
    processId: "p4",
    processName: "Invoice Processing",
    nodeId: "n4",
    impactPercent: 50,
    createdAt: "2026-04-07T10:00:00Z",
  },
];

export const ACTIVITY: ActivityItem[] = [
  {
    id: "a1",
    type: "comment",
    user: "Sarah Chen",
    userInitials: "SC",
    userColor: "#6366f1",
    action: "commented on",
    target: "Plan Selection node",
    processId: "p1",
    timestamp: "2026-04-09T10:23:00Z",
  },
  {
    id: "a2",
    type: "alert",
    user: "System",
    userInitials: "SY",
    userColor: "#ef4444",
    action: "detected bottleneck in",
    target: "Manual Review Queue",
    processId: "p1",
    timestamp: "2026-04-09T08:00:00Z",
  },
  {
    id: "a3",
    type: "edit",
    user: "Marcus Webb",
    userInitials: "MW",
    userColor: "#06b6d4",
    action: "updated",
    target: "Bug Resolution Workflow",
    processId: "p2",
    timestamp: "2026-04-09T08:00:00Z",
  },
  {
    id: "a4",
    type: "version",
    user: "Priya Nair",
    userInitials: "PN",
    userColor: "#10b981",
    action: "published v4 of",
    target: "Customer Onboarding",
    processId: "p1",
    timestamp: "2026-04-07T15:30:00Z",
  },
  {
    id: "a5",
    type: "share",
    user: "Aisha Okafor",
    userInitials: "AO",
    userColor: "#ec4899",
    action: "shared",
    target: "Product Launch Checklist",
    processId: "p3",
    timestamp: "2026-04-07T11:00:00Z",
  },
  {
    id: "a6",
    type: "edit",
    user: "Sarah Chen",
    userInitials: "SC",
    userColor: "#6366f1",
    action: "created",
    target: "Invoice Processing",
    processId: "p4",
    timestamp: "2026-04-01T10:00:00Z",
  },
];

export const EFFICIENCY_TREND: TrendDataPoint[] = [
  { date: "Jan", value: 58, baseline: 60 },
  { date: "Feb", value: 62, baseline: 60 },
  { date: "Mar", value: 59, baseline: 60 },
  { date: "Apr 1", value: 65, baseline: 60 },
  { date: "Apr 7", value: 71, baseline: 60 },
  { date: "Apr 9", value: 74, baseline: 60 },
];

export const CYCLE_TIME_TREND: TrendDataPoint[] = [
  { date: "Jan", value: 88 },
  { date: "Feb", value: 82 },
  { date: "Mar", value: 79 },
  { date: "Apr 1", value: 76 },
  { date: "Apr 7", value: 72 },
  { date: "Apr 9", value: 68 },
];

export const BOTTLENECK_TREND: TrendDataPoint[] = [
  { date: "Jan", value: 8 },
  { date: "Feb", value: 9 },
  { date: "Mar", value: 7 },
  { date: "Apr 1", value: 6 },
  { date: "Apr 7", value: 5 },
  { date: "Apr 9", value: 5 },
];

export const PROCESS_VOLUME: TrendDataPoint[] = [
  { date: "Mon", value: 12 },
  { date: "Tue", value: 18 },
  { date: "Wed", value: 15 },
  { date: "Thu", value: 22 },
  { date: "Fri", value: 19 },
  { date: "Sat", value: 8 },
  { date: "Sun", value: 6 },
];

export const NOTIFICATIONS: Notification[] = [
  {
    id: "notif1",
    type: "bottleneck",
    title: "Critical bottleneck detected",
    description:
      "Manual Review Queue in Customer Onboarding has exceeded SLA by 140%",
    read: false,
    createdAt: "2026-04-09T08:00:00Z",
    processId: "p1",
  },
  {
    id: "notif2",
    type: "comment",
    title: "Sarah Chen mentioned you",
    description: "In Customer Onboarding → Plan Selection: '@Marcus can you look at the conversion data?'",
    read: false,
    createdAt: "2026-04-09T10:23:00Z",
    processId: "p1",
  },
  {
    id: "notif3",
    type: "bottleneck",
    title: "Legal Sign-off still blocked",
    description: "Product Launch Checklist: Legal review at 91 bottleneck score for 48h",
    read: true,
    createdAt: "2026-04-08T12:00:00Z",
    processId: "p3",
  },
];
